
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
  throw new Error('Missing Supabase environment variables. Please check your .env.local file.');
}

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storageKey: 'athena-auth-storage',
    detectSessionInUrl: true,
    flowType: 'pkce'
  },
  db: {
    schema: 'public'
  },
  global: {
    headers: {
      'X-Client-Info': 'athena-academic-system'
    }
  }
});

// Export a function to get the client with custom options if needed
export const getSupabaseClient = (options?: any) => {
  return createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
    ...options,
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      storageKey: 'athena-auth-storage',
      detectSessionInUrl: true,
      flowType: 'pkce',
      ...options?.auth
    }
  });
};
